### ISSUE TITLE
Allowing arbretrary characters within a module name

### ISSUE THREAD

**Issue by Frityet** [hugomg/lua-aot-5.4#15]
Currently, only a small subset of characters are allowed within a module name for luaot in order to make it work within a C symbol name. I had the same issue in a [project I made for packing lua into an executable](https://github.com/Frityet/combustion), in which my solution was [to change every character of the module name](https://github.com/Frityet/combustion/blob/4294fca8c00de9b1979a9d0d9f393488f3208738/src/executables/static.lua#L121C9-L121C77) into [its equivalent hex code](https://github.com/Frityet/combustion/blob/4294fca8c00de9b1979a9d0d9f393488f3208738/src/utilities.lua#L264C1-L264C1) and encoding it that way.
> `/Users/frityet/Documents/combustion/build/lua/pl/pretty.lua -> lua_2F55736572732F667269747965742F446F63756D656E74732F636F6D62757374696F6E2F6275696C642F6C75612F706C2F7072657474792E6C7561`

example of a module being compiled, in my program the entire path is used and the actual require name (`pl.pretty`) is saved as a string, but it can be done with just symbols,

> `pl.pretty -> luaopen_706C2E707265747479`

where the internal searcher introduced in #14 would discover it.

This produces long symbol names, but has guaranteed no collisions compared to a hash function.

**Comment by ghost** [comment]
I am looking for a Lua interpreter clone which would be able to support any Unicode characters (full Unicode range, including private areas) in its variable/symbol names and also allow to rename any build-in functions, keywords and operators within the script code for later usage. No idea if it is here the right place to talk about it ... ?
P.S. The file system supports full Unicode range for the file names ... so why not allow the same for the symbols used in a programming language???

**Comment by hugomg** [comment]
The reason Lua doesn't support other unicode symbols in names is that the data tables to keep track of which characters are allowed would be too large. (Lua wants to keep the implementation very small)

**Comment by ghost** [comment]
I have been through many programming languages and text editors ... currently sticking with Lua after more than 20 years of using Python. I prefer Lua because of the syntax design supporting multi-level string literals and comments and the possibility of running functions without usage of parentheses ...

Is Lua Operating System something worth to check out? Or just a crazy idea in its early stage of confusion ...?

My current point of view on scripting code is that it would be a huge advantage to disallow any Unicode points below 255 values as script code. This way usual text would all be considered whitespace and won't need any marking as comments ... OK ... then you would need a modal editor to type the code, but this would be sure not really a problem.

claudio.grondi@freenet.de ( in case you decide to help me with getting a Lua version supporting the above described idea with what is accepted as valid script code ).

**Comment by hugomg** [comment]
This project is intended to keep as close as possible to upstream Lua.

I don't know what version of Lua to point you to, but surely soneone must have already done something of the sort. I would try searching the Lua mailing list archives.

**Comment by Frityet** [comment]
> Is Lua Operating System something worth to check out? Or just a crazy idea in its early stage of confusion ...?

Im working on this actually
https://github.com/TheLuaOSProject/Kernel

**Comment by Frityet** [comment]
@hugomg Any reason why this isn't planned?

**Comment by hugomg** [comment]
I want to faithfully implement upstream Lua.

**Comment by ghost** [comment]
> This project is intended to keep as close as possible to upstream Lua.
> 
> I don't know what version of Lua to point you to, but surely someone must have already done something of the sort. I would try searching the Lua mailing list archives.

I have just tested and can confirm that LuaJIT ( [https://github.com/LuaJIT/LuaJIT](https://github.com/LuaJIT/LuaJIT) ) interpreter supports Unicode characters in identifiers at any place (also as first "letter"). There is also a project on github [https://github.com/Erutuon/lua-utf8-identifiers](https://github.com/Erutuon/lua-utf8-identifiers) which provides a patch allowing a part of Unicode to be used in identifiers. 
In other words, problem solved, so I don't need to reinvent the wheel. I don't care about sticking to the official Lua version and can take anything that works. Strange, that somehow it took me WEEKS to arrive at this information ... 

By the way: I agree with the notion that adding Unicode identifiers to Lua main official version my be not a good idea. But ... the source is there and LuaJIT is there, and a patch is there ... In other words: who wants it can get it taking responsibility for reasonable use for own custom purposes. Asking for providing it in default Lua in this context obsolete. 

P.S. here a link to a broad discussion of this subject in the far past [https://lua-users.org/lists/lua-l/2019-10/msg00270.html](https://lua-users.org/lists/lua-l/2019-10/msg00270.html) with all the pro- and contra argumentation.
