### ISSUE TITLE
Feature request: module name flag

### ISSUE THREAD

**Issue by hishamhm** [hugomg/lua-aot-5.4#4]
Oh, I just noticed something!

If you run `luaot foo.lua -o foo_aot.c` the module name becomes `foo_aot`, with a symbol `luaopen_foo_aot`.

That's probably an ok default, but in the case of my script I was AOT-compiling `tl.lua` into `tl_module.c` and then linking it into `tl.a` (because I already had another file called `tl.c` for the main chunk).
It could be useful for build script purposes if `luaot` it had a name flag (`-n`?) to override the module name, so that  `luaot foo.lua -n foo -o foo_aot.c` produces `luaopen_foo`. 

Thinking more about it, I think this is even _necessary_ for multi-level module names. If you AOT-compile a module `aaa.bbb.ccc`, the file will be called ccc.lua (or even worse, init.lua inside aaa/bbb/ccc), but the name needs to be `luaopen_aaa_bbb_ccc`. I'd keep the `-n` flag using dots to refer to the requireable name (perhaps even pick `-r` to mean "require name"?) and convert the dots to underscores internally when exporting `luaopen_*`.

**Comment by hugomg** [comment]
Good idea! What do you think about `-m`/ ` --module-name`? Is there some precedent in the Lua ecosystem?

> . If you AOT-compile a module aaa.bbb.ccc, the file will be called ccc.lua (or even worse, init.lua inside aaa/bbb/ccc), but the name needs to be luaopen_aaa_bbb_ccc

I think this might already be working? It looks at the output file name, not at the input file. If the output file is `aaa/bbb/ccc.c` then it should create a `luaopen_aaa_bbb_ccc`.

**Comment by hugomg** [comment]
Implemented in #6.

**Comment by hishamhm** [comment]
> I think this might already be working? It looks at the output file name, not at the input file. If the output file is aaa/bbb/ccc.c then it should create a luaopen_aaa_bbb_ccc.

Ah, I would have never guessed it! Still, that behavior would be weird, since the _shape_ of the argument shouldn't really be what dictates the module name (e.g. having different results when passing `aaa/bbb/ccc.c` or `output/aaa/bbb/ccc.c` would be weird)

Thanks for adding the feature!

**Comment by hugomg** [comment]
When I did that, it was with the assumption that people would call the compiler from the root of the module tree. But maybe that is a weird assumption to make.
