### ISSUE TITLE
Document how to build a standalone executable

### ISSUE THREAD

**Issue by hugomg** [hugomg/lua-aot-5.4#7]
We know that it is possible to do so, because we managed to build a standalone `tl` using the tl standalone bundler. However, it would be nice to document how to do this sort of thing using a more general-purpose tool.

Some candidates:

* https://github.com/jirutka/luapak
* https://github.com/ers35/luastatic
* https://github.com/siffiejoe/lua-amalg

See also: #1

**Comment by Frityet** [comment]
How was this done? I am using the fork with the flag to make a standalone executable

**Comment by hugomg** [comment]
Hmm... I no longer remember how we used the tl bundler >_>

Anyway, I think if we merge that PR we should be able to mark this issue as closed.
